// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoAnalisis.Data;

#nullable disable

namespace ProyectoAnalisis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428231900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asistencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsistencia"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_inscripcion");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean")
                        .HasColumnName("presente");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdInscripcion");

                    b.ToTable("asistencia");
                });

            modelBuilder.Entity("Catering", b =>
                {
                    b.Property<int>("IdCatering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_catering");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCatering"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_personas");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdCatering");

                    b.HasIndex("IdUsuario");

                    b.ToTable("catering");
                });

            modelBuilder.Entity("DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_pedido");
                });

            modelBuilder.Entity("Diploma", b =>
                {
                    b.Property<int>("IdDiploma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_diploma");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiploma"));

                    b.Property<string>("CodigoVerificacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_verificacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_inscripcion");

                    b.HasKey("IdDiploma");

                    b.HasIndex("IdInscripcion");

                    b.ToTable("diploma");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_curso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCurso"));

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_maximo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_horas");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdDocente")
                        .HasColumnType("integer")
                        .HasColumnName("id_docente");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_curso");

                    b.Property<decimal>("PrecioCurso")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_curso");

                    b.HasKey("IdCurso");

                    b.ToTable("curso");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_inscripcion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<int>("IdCurso")
                        .HasColumnType("integer")
                        .HasColumnName("id_curso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("numeric");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("inscripcion");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Asistencia", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("IdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("Catering", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DetallePedido", b =>
                {
                    b.HasOne("Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Diploma", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("IdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Inscripcion", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAnalisis.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoAnalisis.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Curso", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ProyectoAnalisis.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
